### ISSUE TITLE
Gender specification error

### ISSUE THREAD

**Issue by G1ngerAle** [ssantoshp/comp250Tester#24]
All the keywords for "Female" should be "F", but not "M". I've already submitted a pull request to solve this issue.

**Comment by G1ngerAle** [comment]
Lack of reading, :(
My bad....

**Comment by G1ngerAle** [comment]
I think I have to reopen this issue as there might be an error in the instruction they provided.

**Comment by G1ngerAle** [comment]
Please see [#1483](https://edstem.org/us/courses/32649/discussion/2992029)

**Comment by SamZhang02** [comment]
> All the keywords for "Female" should be "F", but not "M". I've already submitted a pull request to solve this issue.

I think you meant "W" here, not "M", right?

**Comment by G1ngerAle** [comment]
> 

Yep. Sorry for this.
